### ISSUE TITLE
Install events are reported with a lag

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/updater#131]
We report install events on the next patch check, which is typically the next launch of the app.  But we use the date of that launch, rather than when the actual install occurred.

This can create confusion for users of the console:
https://github.com/shorebirdtech/shorebird/issues/1753#issuecomment-1968406611

I suspect we should include some sort of date in the event:
https://github.com/shorebirdtech/updater/blob/main/library/src/events.rs#L42

**Comment by eseidel** [comment]
Specifically we should report events with the *device* time, rather than showing them in our console with the *server* received time.  That will cause spurious events when devices have bad clocks, but it's better than the current data.

**Comment by eseidel** [comment]
See also https://github.com/shorebirdtech/shorebird/issues/2139

**Comment by tristdrum** [comment]
Hey @eseidel! Instead of tracking users device time, wouldn't it make more sense to continue to track the server time when the users device installed the patch, and then simply showing the graph in the admin users time zone?

Otherwise, if we don't take into account timezones properly, we might see installs on the graph that happened hours apart appear right next to each other (e.g. 9am in Texas vs 9am in New York)

Also, here in Africa assuming a users device has the correct time is far from a guarantee 😂

Love your work! Thank you for doing this all in the public! Hope to contribute and be of value to you!

Hoping to implement in the next week. Been following for months! Very exciting times.

**Comment by bryanoltman** [comment]
An update on this, since it's been in the "todo" lane for a bit:

What we currently report is when a patch was marked as "good" (i.e., when we were able to successfully boot from it). The time of this event is what we use to determine which billing period a patch should apply to (we only want to bill customers for successful patch installs). This event is sent to the server when the boot is successful (there is no delay between a patch successfully booting and this event being reported).

I believe most of the customer confusion comes from the fact that this is not reporting a _download_ event. A common case is that a user will deactivate a patch and then be confused when patch installs are still being reported. What is happening in these cases is that the patch was downloaded prior to deactivation, but was only successfully booted from when the user restarted the app after the patch was deactivated.

What we should probably do is to start reporting download events separately from install events. This would provide us (Shorebird) with useful information (how many users get patches and never install them?) as well as making this distinction clearer to users.

**Comment by eseidel** [comment]
I think it's slightly worse than that, there are 3 times:
1. download & install
2. boot
3. event actually reaches our servers (since internet might have been off during boot)

Right now we only record 3 (in server time), I think customers are expecting 1. (which probably means recording in device time, even though device time isn't necessarily reliable).  So maybe we should just record/report 2 or 3 of those times and sort it out server side 🤷

**Comment by bryanoltman** [comment]
We've update the console to report downloads and installs separately, which should help clear up this confusion. Closing.
